### ISSUE TITLE
Port pandas helper module for data from pycompwa

### ISSUE THREAD

**Issue by spflueger** [ComPWA/ampform#3]
The new data module in `pycompwa` by @redeboer already provides all of the needed functionality.
From that existing data module, only a fraction of the code and functionality is needed though. Here one should also be careful not to port the flaws imposed by the design of ComPWA (`EventCollection`).

_Update:_
The `expertsystem` now has its own `data` module. Some of the features of `pycompwa` could be added here, especially if we allow to have `to_pandas()` return an actual `DataFrame`. `EventCollection.to_pandas()` already formats to the standards set by the `PwaAccessor` that `pycompwa` used, so it would just be a matter of porting the `PwaAccessor` and casting the output `dict` of `to_pandas()` to `pandas.DataFrame`.

**Comment by redeboer** [comment]
Made redundant by #92. If needed, this issue could be reopened in a (future) wrapper packages about QRules, AmpForm, and TensorWaves.
