### ISSUE TITLE
Document origin of Wigner-D(-phi, theta, 0)

### ISSUE THREAD

**Issue by redeboer** [ComPWA/ampform#308]
The function that formulates Wigner-$D$ functions for two-body decay nodes, [`formulate_wigner_d()`](https://ampform.readthedocs.io/en/0.14.x/api/ampform.helicity.html#ampform.helicity.formulate_wigner_d), currently returns $D({\color{red}-}\phi, \theta, 0)$. As noted by @mmikhasenko, this is not in Kutschke or any other papers. Usually, it's either:
1. $D(\phi, \theta, -\phi)$: [Jacob & Wick 1959](https://linkinghub.elsevier.com/retrieve/pii/000349165990051X) Eq (24), [Kutschke 1996](https://home.fnal.gov/~kutschke/Angdist/angdist.ps) Eq (10), [Richman 1984](https://inspirehep.net/literature/202987) [Eq (4.17)](https://lib-extopc.kek.jp/preprints/PDF/1984/8409/8409198.pdf#page=18)
2. $D(\phi, \theta, 0)$: [Chung 2014 Eq (4.16)](https://suchung.web.cern.ch/spinfm1.pdf#page=16)

**Comment by mmikhasenko** [comment]
Yes, the 2 make perfect sense. It is the same D-matrix

**Comment by mmikhasenko** [comment]
The only complexity in the D-matrix is the azimuthal dependence. Hence, the conjugation is equivalent to flipping the sign of the phi

<img width="548" alt="image" src="https://user-images.githubusercontent.com/22725744/176842283-8d4b6ee0-eaa3-4547-8e26-f002907a41c9.png">


<img width="451" alt="image" src="https://user-images.githubusercontent.com/22725744/176842366-6b4a8eb5-30d6-4e8b-917d-4010ed7e30c2.png">

**Comment by mmikhasenko** [comment]
As an example, you need at least 4 body decay with two different decay chains interfering.
phi -> -phi will change the sign of the interference term.
The sign of this interference is unambiguously fixed in case of identical particles in the final state.

4pi0 might be the simplest system. Checking what sign is physical might be non-trivial.

**Comment by mmikhasenko** [comment]
See also the page 199 where they shift the convention to the (phi, theta, 0)

**Comment by mmikhasenko** [comment]
The discussion I refer to in the Martin Spearman is above Eq. (3.48)
