### ISSUE TITLE
Symbolic expression for `BlattWeisskopfSquared` for arbitrary L

### ISSUE THREAD

**Issue by mmikhasenko** [ComPWA/ampform#417]
### Problem description

Polynomials in the `BlattWeisskopfSquared` [implementation](https://github.com/ComPWA/ampform/blob/c190cb055314813dfaa547f2dd456d1a15e87079/src/ampform/dynamics/__init__.py#L66-L134) are complicated.

### Proposed solution

They can be replaced by symbolic expressions
![image](https://github.com/ComPWA/ampform/assets/22725744/f1fe2824-70ee-4e78-b78c-732d8606da48)
(the screenshot is from a [review](https://arxiv.org/pdf/1909.06366))

**Comment by redeboer** [comment]
Thanks for the reference, that's great! Indeed would be super easy to implement this with SymPy it seems. And will also make the lamdification for parametrized $l$ way nicer than this casewise implementation

**Comment by redeboer** [comment]
First some clarity on the notation of

```math
F_l^2(z) = \frac{1}{z\left|h^{(1)}_l\left(q/q_R\right)\right|^2}.
```

With the definition $z(s) = \left\[q(s)/q_R\right\]^2$, does that mean we get

```math
F_l^2(z) = \frac{1}{z\left|h^{(1)}_l(z)\right|^2}\,?
```

(If I strictly replace though, it would be something like $q/q_R=\pm\sqrt{z}$.)

If so, does this mean the 'Hankel-normalized' Blatt–Weisskopf factor, like in [10.1002/andp.19955070504](https://doi.org/10.1002/andp.19955070504), p.&nbsp;415 (in AmpForm [denoted](https://ampform.readthedocs.io/0.15.x/api/ampform.dynamics/#ampform.dynamics.BlattWeisskopfSquared) $B^2_l$) becomes

```math
B_l^2(z) = \frac{z^l\left|h^{(1)}_l(1)\right|^2}{z\left|h^{(1)}_l(z)\right|^2}\,?
```

It's a bit handwaving here — trying to get the same order of $z$ in the nominator and getting that factor in front from the Hankel function.

**Comment by redeboer** [comment]
Unfortunately it seems that SymPy's [`hankel1`](https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.bessel.hankel1) has no algebraic implementation for specific $l$ or $z$ values for $h_l^{(1)}(z)$. (I assume $H$ is just the same as $h$). The expression class lambdifies to [`scipy.special.hankel1`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.hankel1.html).

![image](https://github.com/ComPWA/ampform/assets/29308176/086a714a-02ec-497d-b5b3-cf20291fd059)

But if [Equation (96)](https://github.com/ComPWA/ampform/issues/417#issue-2293280871) is sufficient, we could implement a specialized `Hankel1` expression class that evaluates to that series.

**Comment by redeboer** [comment]
> if [Equation (96)](https://github.com/ComPWA/ampform/issues/417#issue-2293280871) is sufficient, we could implement a specialized `Hankel1` expression class that evaluates to that series.
> https://github.com/ComPWA/ampform/issues/417#issuecomment-2109569629

With a custom `Hankel1` class and some hacking to avoid letting the `sympy.Sum` evaluate if $l$ is symbolic, I get:

![image](https://github.com/ComPWA/ampform/assets/29308176/61f0e4eb-845f-48b5-9d7f-66e969a27ef5)


> If I strictly replace though, it would be something like $q/q_R=\pm\sqrt{z}$.
> 
> https://github.com/ComPWA/ampform/issues/417#issuecomment-2109554861

To get the same polynomials as in [the current implementation](https://ampform.readthedocs.io/0.15.x/api/ampform.dynamics/#ampform.dynamics.BlattWeisskopfSquared), this indeed required using $h_l^{(1)}\left(\sqrt{z}\right)$.
![image](https://github.com/ComPWA/ampform/assets/29308176/93c9db45-e236-4221-aa2d-ed79922557c4)
