### ISSUE TITLE
canonical-helicity may be wrong

### ISSUE THREAD

**Issue by jiangyi15** [ComPWA/ampform#73]
## Bug description

canonical-helicity may be wrong.

## How to reproduce?

1.
```
import qrules as q
from ampform import get_builder
import sympy as sym

result = q.generate_transitions(        
     initial_state="D(1)(2420)0",        
     final_state=["K+","K-","K~0"],      
     allowed_intermediate_particles=["a(1)(1260)+"],
     formalism_type="canonical-helicity")

modol_builder = get_builder(result)
model_no_dynamics = modol_builder.generate()
model_no_dynamics.expression
```

## Expected behavior

Parameters named with LS coupling.

## System info

Bug resulted on the following system:

[https://mybinder.org/v2/gh/ComPWA/ampform/stable?filepath=docs/usage](https://mybinder.org/v2/gh/ComPWA/ampform/stable?filepath=docs/usage)

- OS: Ubuntu
- Version 20.04
- Python version: 3.7
- Virtual environment: pip user install

**Comment by jiangyi15** [comment]
see https://github.com/jiangyi15/tf-pwa/issues/42

**Comment by redeboer** [comment]
Hi @jiangyi15, nice to hear from you and thanks for the bug report! Also thanks for your helpful comment https://github.com/jiangyi15/tf-pwa/issues/42#issuecomment-844231247, I somehow hadn't subscribed to that issue and missed it.

Let me investigate a bit -- some things have changed since that issue and it's also the question whether it's just a problem with notation or that really the wrong terms are added up here. I'll get back to you later!

**Comment by jiangyi15** [comment]
The symbol is defined in [`coefficient_symbol = sp.Symbol(f"C[{suffix}]")`](https://github.com/ComPWA/ampform/blob/main/src/ampform/helicity.py#L622).
So, the simple way to fix this is to implement  
[`generate_sequential_amplitude_suffix`](https://github.com/ComPWA/ampform/blob/main/src/ampform/helicity.py#L270) for [`_CanonicalAmplitudeNameGenerator`](https://github.com/ComPWA/ampform/blob/main/src/ampform/helicity.py#L622).
But, I am not sure if there is some other effect.

**Comment by redeboer** [comment]
Ok yes, that's where the coefficient labeling could be fixed.
So with https://github.com/jiangyi15/tf-pwa/issues/42#issuecomment-844231247 you mean to say that the labeling scheme that AmpForm currently uses to name coefficient names in the canonical helicity formalism results in duplicate coefficient names (and therefore identical SymPy symbols), while these coefficients should be distinguishable?

**Comment by jiangyi15** [comment]
These coefficients should be distinguished by angular momentum instead of helicity. Use the same coefficient for the same angular momentum (LS).

**Comment by jiangyi15** [comment]
You can see that the formula now can combine the CG series first, and then product the coeffiences and D matrix.
![Screenshot_20210519_232545](https://user-images.githubusercontent.com/61738047/118839992-94568e00-b8f9-11eb-85b6-80010ec39d15.png)
 But the right one should cross the CG parts and coeffieiences.
![Screenshot_20210519_234509](https://user-images.githubusercontent.com/61738047/118843087-4bec9f80-b8fc-11eb-9f7c-424cbbac5de6.png)

**Comment by redeboer** [comment]
Yes, so if I understand correctly, you propose to extend the labeling to also include angular momentum in the coefficient names? Do you also think the spin projections in the above screenshot should be removed, or only _l=_ added to it?

**Comment by jiangyi15** [comment]
The spin projection (it means helicity here) of intermediate states should be remove. The sum of helicity should be replaced by sum of LS (anglur momentum).
